#!/usr/bin/env ruby

ONE_LOCATION=ENV["ONE_LOCATION"] if !defined?(ONE_LOCATION)

if !ONE_LOCATION
    RUBY_LIB_LOCATION="/usr/lib/one/ruby" if !defined?(RUBY_LIB_LOCATION)
else
    RUBY_LIB_LOCATION=ONE_LOCATION+"/lib/ruby" if !defined?(RUBY_LIB_LOCATION)
end

$: << RUBY_LIB_LOCATION
$: << File.dirname(__FILE__)

require 'az_driver'

deploy_id = ARGV[0]
file      = ARGV[1]
host      = ARGV[2]

az_drv = AzureDriver.new(host)
begin
    az_drv.save(deploy_id)
rescue => e
    STDERR.puts "Error saving Azure VM [#{deploy_id}]: " + e.message
    exit -1
end