#!/usr/bin/env ruby

ONE_LOCATION = ENV["ONE_LOCATION"] if !defined?(ONE_LOCATION)

if !ONE_LOCATION
    RUBY_LIB_LOCATION = "/usr/lib/one/ruby" if !defined?(RUBY_LIB_LOCATION)
    ETC_LOCATION      = "/etc/one/" if !defined?(ETC_LOCATION)
else
    RUBY_LIB_LOCATION = ONE_LOCATION + "/lib/ruby" if !defined?(RUBY_LIB_LOCATION)
    ETC_LOCATION      = ONE_LOCATION + "/etc/" if !defined?(ETC_LOCATION)
end

$: << RUBY_LIB_LOCATION

require 'azure_driver'

deploy_id = ARGV[0]
host      = ARGV[1]
id        = ARGV[2]

client = AzureDriver::Client.new(host)

### END ###

### setting ONe vars ### 
POLL_ATTRIBUTE  = VirtualMachineDriver::POLL_ATTRIBUTE
VM_STATE        = VirtualMachineDriver::VM_STATE
### END ###


result, poll_data = client.poll deploy_id

begin
    puts result
rescue => e
    STDERR.puts "Error polling Azure VM [#{deploy_id}]: " + e.message
    exit -1
end
